import '~/styles/globals.css';

import type { Metadata } from 'next';
import { Alice, Playfair_Display } from 'next/font/google';

import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
    title: 'Create T3 App',
    description: 'Generated by create-t3-app',
    icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const playfairDisplay = Playfair_Display({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-playfair-display',
});

const alice = Alice({
    subsets: ['latin', 'cyrillic'],
    weight: '400',
    variable: '--font-alice',
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang={'en'} className={`${playfairDisplay.variable} ${alice.variable}`}>
            <body>
                <TRPCReactProvider>{children}</TRPCReactProvider>
            </body>
        </html>
    );
}
